CREATE TABLE VERKAUF 
(
  ANZAHL NUMBER 
, DATUM DATE 
, VERKAUFID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) NOT NULL
, FILIALID NUMBER NOT NULL  
, VERK훃FERID NUMBER NOT NULL 
, PRODUKTID NUMBER NOT NULL 
, KUNDENID NUMBER NOT NULL 
, CONSTRAINT FILIALE_FK FOREIGN KEY(FILIALID) REFERENCES FILIALE(FILIALID)
, CONSTRAINT PRODUKT_FK FOREIGN KEY(PRODUKTID) REFERENCES PRODUKT(PRODUKTID)
, CONSTRAINT KUNDEN_FK FOREIGN KEY(KUNDENID) REFERENCES KUNDE(KUNDENID)
, CONSTRAINT VERK훃FER_FK FOREIGN KEY(VERK훃FERID) REFERENCES VERK훃FER(VERK훃FERID)
, CONSTRAINT VERKAUF_PK PRIMARY KEY 
  (
    VERKAUFID 
  )
)
