CREATE TABLE FILIALE 
(
  FILIALLEITER VARCHAR2(20 BYTE) 
, FILIALID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) NOT NULL
, STADT VARCHAR2(20 BYTE) 
, LAND VARCHAR2(20 BYTE) 
, BEZIRK VARCHAR2(20 BYTE) 
, CONSTRAINT FILIALE_PK PRIMARY KEY 
  (
    FILIALID 
  )
)
