CREATE TABLE PRODUKT 
(
  PREIS NUMBER 
, BEZEICHNUNG VARCHAR2(20 BYTE)
, PRODUKTID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) NOT NULL
, PRODUKTGRUPPE VARCHAR2(20 BYTE) 
, HNAME VARCHAR2(20 BYTE)
, LAND VARCHAR2(20 BYTE)
, CONSTRAINT PRODUKT_PK PRIMARY KEY 
  (
    PRODUKTID 
  )
)
