CREATE TABLE VERK훃FER 
(
  VERK훃FERID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) NOT NULL
, NAME VARCHAR2(20 BYTE) 
, GEB DATE 
, FACHGEBIET VARCHAR2(20 BYTE) 
, CONSTRAINT VERK훃FER_PK PRIMARY KEY 
  (
    VERK훃FERID 
  )
) 
